image: docker:stable

stages:
  - build
  - deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  DOCKER_DRIVER: overlay2
  SERVICE_NAME: church

before_script:
  - docker info
  - 'which ssh-agent || apk add openssh-client'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir ~/.ssh
  - ssh-keyscan $PROD_IP >~/.ssh/known_hosts

build:
  stage: build
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CONTAINER_IMAGE
    - docker tag $CONTAINER_IMAGE $CI_REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest

deploy:
  stage: deploy
  script:
    - echo "Deploying $CONTAINER_IMAGE to $SERVICE_NAME"
    - docker image save $CI_REGISTRY/$CI_PROJECT_PATH:latest | ssh $PROD_USER@$PROD_IP docker load
    - ssh $PROD_USER@$PROD_IP "docker-compose -f /srv/docker/docker-compose.yml up -d nginx"
  only:
    - master